services:
  bewerbung:
    image: "bewerbung:latest"
    ports:
      - "3000:3000"
    env_file: ".env.prod"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: always
    networks:
      - bewerbung
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - bewerbung
networks:
  bewerbung:
volumes:
  db:
